CREATE TABLE  IF NOT EXISTS houses (
    listDate TEXT NOT NULL ,
    mlsNo TEXT NOT NULL ,
    images JSON NOT NULL ,
    showImage TEXT NOT NULL ,
    area TEXT NOT NULL DEFAULT '' ,
    country TEXT NOT NULL ,
    streetName INT NOT NULL ,
    city TEXT NOT NULL ,
    streetNumber INT NOT NULL ,
    unitNumber INT NULL ,
    streetSuffix INT NOT NULL ,
    neighborhood TEXT NOT NULL ,
    state TEXT NOT NULL ,
    streetDirection TEXT NULL ,
    addressLine1 TEXT NOT NULL ,
    addressLine2 TEXT NOT NULL ,
    fullAddress TEXT NOT NULL ,
    soldDate TEXT NULL ,
    soldPrice INT NULL ,
    parkingSpaces INT NOT NULL DEFAULT '0' ,
    bathrooms INT NOT NULL DEFAULT '0' ,
    bathroomsPlus INT NOT NULL DEFAULT '0' ,
    bedrooms INT NOT NULL DEFAULT '0' ,
    bedroomsPlus INT NOT NULL DEFAULT '0' ,
    propertyType TEXT NOT NULL ,
    squareFeet INT NOT NULL DEFAULT '0' ,
    style TEXT NOT NULL ,
    garrageSpaces INT NOT NULL ,
    listPrice INT NOT NULL ,
    lastStatus TEXT NOT NULL ,
    status TEXT NOT NULL ,
    boardId INT NOT NULL ,
    link TEXT NOT NULL ,
    offerPrice INT NOT NULL DEFAULT '0' ,
    offerDescription TEXT NOT NULL DEFAULT 'Currently no offer' ,
    showStatus INT NOT NULL 
) 